# Generated by Django 5.2.17 on 2026-09-13 04:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery (COD)', 'Cash on Delivery (COD)'), ('UPI (Google Pay / PhonePe / Paytm)', 'UPI (Google Pay / PhonePe / Paytm)'), ('Credit / Debit Card (Visa / Mastercard / RuPay)', 'Credit / Debit Card (Visa / Mastercard / RuPay)'), ('Net Banking', 'Net Banking (All Major Indian Banks)')], default='UPI (Google Pay / PhonePe / Paytm)', max_length=80),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
    ]
